"""
Django settings for StateGridTraffic project.

Generated by 'django-admin startproject' using Django 4.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-!@a@dn9jzjavn42%!5&!rdqfrk2*6sv)t*+219i0vl5%cfk0*a'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

# genIPImage、predSQL
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # 以下新增
    'corsheaders',
    'classify',
    "detect",
    'user',
    'rest_framework',
    'django_crontab',
    'packet_dissect',
]

CRONJOBS = [
    ('0 0,6,12,18 * * * flock -xn '+ os.path.join(BASE_DIR, 'logs/auto_update_image.log'), 'detect.models.run_auto_update_image', '>>' + os.path.join(BASE_DIR, 'logs/auto_update_image.log')),
    ('40 */5 * * * flock -xn '+ os.path.join(BASE_DIR, 'logs/n4j_persona.log'), 'detect.persona.run', '>>' + os.path.join(BASE_DIR, 'logs/n4j_persona.log')),
    ('0 */3 * * * flock -xn '+ os.path.join(BASE_DIR, 'logs/n4j_start.log'), 'detect.start.run', '>>' + os.path.join(BASE_DIR, 'logs/n4j_start.log')),
    ('0 3,9,15,21 * * * flock -xn '+ os.path.join(BASE_DIR, 'logs/auto_model_pred.log'), 'classify.models.run_auto_model_pred', '>>' + os.path.join(BASE_DIR, 'logs/auto_model_pred.log')),
    ('*/5 * * * * flock -xn '+ os.path.join(BASE_DIR, 'logs/auto_delete.log'), 'detect.models.auto_delete', '>>' + os.path.join(BASE_DIR, 'logs/auto_delete.log')),
    ('*/15 * * * * flock -xn '+ os.path.join(BASE_DIR, 'logs/auto_delete_pcap.log'), 'detect.models.auto_delete_pcap', '>>' + os.path.join(BASE_DIR, 'logs/auto_delete_pcap.log'))
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
# 跨域请求问题
CORS_ORIGIN_ALLOW_ALL = True
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOWED_ORIGINS_REGEXES=[
    r'^http://.*?$',
]


CORS_ALLOW_METHODS = ('*')
CORS_ALLOW_METHODS = (
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
    'VIEW',
)
 
CORS_ALLOW_HEADERS = ('*')

ROOT_URLCONF = 'StateGridTraffic.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['/web/packet_info'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'StateGridTraffic.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',  # 数据库引擎
        'NAME': os.environ['MYSQL_DATABASE'],  # 数据库名称
        'HOST': os.environ['MYSQL_HOST'], # 服务器地址，如果是本地可以写127.0.0.1
        'PORT': os.environ['MYSQL_PORT'],
        'USER': os.environ['MYSQL_USER'],
        'PASSWORD': os.environ['MYSQL_PASSWORD'],
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = ['/web/packet_info/static']

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": f"redis://:{os.environ['REDIS_PASSWORD']}@{os.environ['REDIS_HOST']}:{os.environ['REDIS_PORT']}/{os.environ['REDIS_DB']}",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "COMPRESSOR": "django_redis.compressors.lzma.LzmaCompressor",
        }
    }
}