name: Snyk Security

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read
  security-events: write

jobs:
  snyk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Check Dockerfile Existence
        id: dockerfile-check
        run: |
          if [ -f "Dockerfile" ]; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Setup Snyk CLI
        uses: snyk/actions/setup@v1.0.0
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      # SAST Scanning
      - name: Run Code Analysis
        run: |
          snyk code test --sarif > snyk-code.sarif || echo "SAST scan completed with warnings"
        continue-on-error: true

      # SCA Scanning 
      - name: Run Dependency Scan
        run: |
          snyk test --all-projects --sarif > snyk-deps.sarif || echo "SCA scan completed with warnings"
          snyk monitor --all-projects || true
        continue-on-error: true

      # IaC Scanning
      - name: Run Infrastructure Scan
        run: |
          snyk iac test --sarif > snyk-iac.sarif || echo "IaC scan completed with warnings"
        continue-on-error: true

      # Conditional Container Scanning
      - name: Build Docker Image
        if: ${{ steps.dockerfile-check.outputs.exists == 'true' }}
        run: docker build -t snyk-container-scan . || true

      - name: Run Container Scan
        if: ${{ steps.dockerfile-check.outputs.exists == 'true' }}
        run: |
          snyk container test snyk-container-scan --file=Dockerfile --sarif > snyk-container.sarif || true
          snyk container monitor snyk-container-scan --file=Dockerfile || true
        continue-on-error: true

      # Report Upload
      - name: Upload Security Reports
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: |
            snyk-code.sarif
            snyk-deps.sarif
            snyk-iac.sarif
            snyk-container.sarif
        continue-on-error: true

      # Final Success
      - name: Force Pipeline Success
        if: always()
        run: exit 0
