name: pull_request
on:
  # 添加push事件触发器
  push:
    branches:
      - master
      - 'release-**'
  pull_request:
    types: [synchronize, reopened, labeled]
    branches:
      - master
      - 'release-**'

concurrency:
  # 适配两种事件的并发控制
  group: ${{ github.event_name == 'pull_request' && github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: lint
    # 修改触发条件适配push事件
    if: |
      (github.event_name == 'push') ||
      (contains(github.event.pull_request.labels.*.name, 'ready-for-testing') &&
       github.event.pull_request.merged != true)
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
        with:
          # 动态获取基准commit
          ref: ${{ github.event_name == 'pull_request' && github.event.pull_request.base.sha || github.sha~1 }}
      # 其余lint步骤保持不变...

  build:
    name: build
    needs: lint
    # 保持原有环境矩阵不变
    strategy:
      fail-fast: false
      matrix:
        os: [centos7, ubuntu2004]
        compiler: [gcc-9.3, clang-10]
        exclude:
          - os: centos7
            compiler: clang-10
        include:
          - os: centos7
            compiler: gcc-9.3
            required: true
          - os: ubuntu2004
            compiler: gcc-9.3
            required: false
          - os: ubuntu2004
            compiler: clang-10
            required: false

    # 所有测试步骤保持不变...
    steps:
      # ... [原有构建步骤] ...

      # 单元测试（保持原有分割逻辑）
      - name: CTest
        run: |
          ctest -j $(($(nproc)/2+1)) --timeout 400 -LE segment_id_test
          ctest -j $(($(nproc)/2+1)) --timeout 400 -L segment_id_test

      # 集成测试（保留所有类型）
      - name: Pytest
        run: make test  # 保持参数不变

      # 兼容性测试
      - name: TCK
        run: make tck   # 保留ES集成参数

      # 性能测试
      - name: LDBC
        run: make ldbc  # 参数不变

      # 强制关键环境验证
      - name: Validate CentOS
        if: ${{ matrix.required && always() }}
        run: |
          if [ "${{ job.status }}" != 'success' ]; then
            echo "::error::CentOS环境验证失败"
            exit 1
          fi

      # 结果处理（保持原有逻辑）
      - uses: codecov/codecov-action@v3
        if: ${{ matrix.os == 'ubuntu2004' && matrix.compiler == 'gcc-9.3' }}
      
      - name: Upload Logs
        uses: actions/upload-artifact@v4
        if: ${{ failure() }}
