ame: pull_request
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read
  security-events: write

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os: [centos7, ubuntu2004]
        compiler: [gcc-9.3, clang-10]
        exclude:
          - os: centos7
            compiler: clang-10
        include:
          - os: centos7
            compiler: gcc-9.3
            required: true
          - os: ubuntu2004
            compiler: gcc-9.3
            required: false
          - os: ubuntu2004
            compiler: clang-10
            required: false

    steps:
      - name: CMake
        id: cmake
        run: make RM_DIR=false DEBUG=false ENABLE_FT_INDEX=true ES_ADDRESS='"elasticsearch":9200' J=8 cmake
        working-directory: build/  

      - name: Make
        run: make RM_DIR=false DEBUG=false ENABLE_FT_INDEX=true ES_ADDRESS='"elasticsearch":9200' J=8 make
        working-directory: build/  

      - name: Make
        run: make RM_DIR=false DEBUG=false ENABLE_FT_INDEX=true ES_ADDRESS='"elasticsearch":9200' J=8 make
        working-directory: build/
        
      - name: Ctest
        run: make RM_DIR=false DEBUG=false ENABLE_FT_INDEX=true ES_ADDRESS='"elasticsearch":9200' J=8 ctest
        working-directory: tests/

      - name: Setup cluster
        run: |
          case "${{ matrix.compiler }}" in
          gcc-*)
            case "${{ matrix.os }}" in
            centos7)
              make CONTAINERIZED=true ENABLE_FT_INDEX=true ES_ADDRESS='"elasticsearch":9200' up
              ;;
            ubuntu2004)
              make CONTAINERIZED=true ENABLE_FT_INDEX=true ES_ADDRESS='"elasticsearch":9200' ENABLE_SSL=true CA_SIGNED=true up
              ;;
            esac
            ;;
          clang-*)
            make CONTAINERIZED=true ENABLE_FT_INDEX=true ES_ADDRESS='"elasticsearch":9200' ENABLE_SSL=false ENABLE_GRAPH_SSL=true up
            ;;
          esac
        working-directory: tests/

      - name: Pytest
        run: make RM_DIR=false DEBUG=false ENABLE_FT_INDEX=true ES_ADDRESS='"elasticsearch":9200' J=8 pytest
        working-directory: tests/

      - name: TCK
        run: make RM_DIR=false DEBUG=false ENABLE_FT_INDEX=true ES_ADDRESS='"elasticsearch":9200' J=8 tck
        working-directory: tests/

      - name: LDBC
        run: make RM_DIR=false DEBUG=false J=8 ldbc
        working-directory: tests/

      - name: Tear down cluster
        run: make RM_DIR=false down
        working-directory: tests/

      - name: Upload logs
        uses: actions/upload-artifact@v4
        if: ${{ failure() }}
        with:
          name: ${{ matrix.os }}-${{ matrix.compiler }}-logs
          path: |
            ./build/server_*/logs/
            ./tests/logs/    
